version: '3.8'

volumes:
  mongo-volume:

services:
  nest:
    container_name: nest_api
    restart: always
    build: nest/
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PORT=${NEST_PORT}
    ports:
      - ${NEST_PORT}:${NEST_PORT}
    command: npm run start:dev
    links:
      - mongodb
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./mongo-volume:/data/db
  vue:
    container_name: vue_app
    restart: always
    build: vue/
    ports:
      - "80:80"