version: '3.8'

volumes:
  pandora-data:
    external: true

services:
  web:
    image: ${PANDORA_IMAGES_PREFIX}web:${PANDORA_IMAGES_TAG}
    build: ./vue/
    restart: unless-stopped
    environment:
      - API_URI=${PANDORA_API_URI}
    ports:
      - 127.0.0.1:${PANDORA_WEB_PORT}:8080

  api:
    image: ${PANDORA_IMAGES_PREFIX}api:${PANDORA_IMAGES_TAG}
    build: ./nest/
    restart: unless-stopped
    environment:
      - DB_URI=mongodb://${PANDORA_DB_USER}:${PANDORA_DB_PASSWORD}@db:27017/${PANDORA_DB_NAME}?authSource=admin
      - JWT_SECRET=${PANDORA_JWT_SECRET}
      - JWT_EXPIRES_IN=${PANDORA_JWT_EXPIRES_IN}
      - API_PORT=${PANDORA_API_PORT}
    ports:
      - 127.0.0.1:${PANDORA_API_PORT}:${PANDORA_API_PORT}
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${PANDORA_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${PANDORA_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${PANDORA_DB_PASSWORD}
    ports:
      - ${PANDORA_DB_PORT}:27017
    volumes:
      - type: volume
        source: pandora-data
        target: /data/db
