version: '3.8'

volumes:
  data:
    external: true

services:
  web:
    image: ${PANDORA_IMAGES_PREFIX}web:${GITHUB_RUN_ID}
    build: ./vue/
    restart: unless-stopped
    environment:
      API_URL=http://api:${PANDORA_API_PORT}
    ports:
      - ${PANDORA_WEB_PORT}:80

  api:
    image: ${PANDORA_IMAGES_PREFIX}api:${GITHUB_RUN_ID}
    build: ./nest/
    restart: unless-stopped
    environment:
      - DB_URI=mongodb://${PANDORA_DB_USER}:${PANDORA_DB_PASSWORD}@db:27017/${PANDORA_DB_NAME}?authSource=admin
      - JWT_SECRET=${PANDORA_JWT_SECRET}
      - JWT_EXPIRES_IN=${PANDORA_JWT_EXPIRES_IN}
      - API_PORT=${PANDORA_API_PORT}
    ports:
      - ${PANDORA_API_PORT}:${PANDORA_API_PORT}
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${PANDORA_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${PANDORA_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${PANDORA_DB_PASSWORD}
    ports:
      - ${PANDORA_DB_PORT}:27017
    volumes:
      - type: volume
        source: data
        target: /data/db
