version: '3.8'

volumes:
  nest_volume:

services:
  dev:
    container_name: nest_api
    restart: always
    build: nest/
    ports:
      - 5000:5000
    volumes:
      - nest_volume:/usr/src/app
    command: npm run start:dev