version: '3.8'

services:
  dev:
    container_name: nest_api
    image: nest
    build:
      context: ./nest
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    command: npm run start:dev