- hosts: pandora
  user: admin
  become_method: sudo
  vars:
    loki_version: "2.3.0"
    promtail_version: "{{ loki_version }}"
    loki_port: 3100
  tasks:

    - name: loki service
      block:
        - name: actual loki config is in the volume
          command:
            cmd: docker run --rm -iv loki-config:/v busybox sh -c 'cat > /v/config.yaml'
            stdin: "{{ lookup('template', 'loki-config.yaml.j2') | regex_replace('\\r\\n', '\\n') }}"

        - name: got loki container info
          docker_container_info:
            name: loki
          register: loki_container

        - name: remove existing loki container
          docker_container:
            name: loki
            state: absent
          when: loki_container.exists

        - name: loki up
          docker_compose:
            project_name: loki
            pull: yes
            definition:
              version: '3.8'
              services:
                app:
                  container_name: loki
                  image: grafana/loki:{{ loki_version }}
                  command: -config.file=/etc/loki/config.yaml
                  volumes:
                    - loki-config:/etc/loki
                    - loki-storage:/loki
                  restart: unless-stopped
                  # ports: [ "127.0.0.1:{{ loki_port }}:3100" ]
              volumes:
                loki-config:
                  name: loki-config
                  external: true
                loki-storage:
                  name: loki-storage
                  external: true
              networks:
                default:
                  external: true
                  name: "{{ monitoring_network_name }}"
      tags: loki-service


    - name: promtail service
      block:
        - name: actual promtail config is in the volume
          command:
            cmd: docker run --rm -iv promtail-config:/v busybox sh -c 'cat > /v/config.yml'
            stdin: "{{ lookup('template', 'promtail-config.yml.j2') | regex_replace('\\r\\n', '\\n') }}"

        - name: got promtail container info
          docker_container_info:
            name: promtail
          register: promtail_container

        - name: remove existing promtail container
          docker_container:
            name: promtail
            state: absent
          when: promtail_container.exists

        - name: promtail up
          docker_compose:
            project_name: promtail
            pull: yes
            definition:
              version: '3.8'
              services:
                app:
                  container_name: promtail
                  image: grafana/promtail:{{ promtail_version }}
                  command: -config.file=/etc/promtail/config.yml
                  # ports: [ "9080:9080" ]
                  volumes:
                    - promtail-config:/etc/promtail
                    - promtail-positions:/var/promtail
                    - /var/log:/var/log
                  restart: unless-stopped
              volumes:
                promtail-config:
                  name: promtail-config
                  external: true
                promtail-positions:
                  name: promtail-positions
                  external: true
              networks:
                default:
                  external: true
                  name: "{{ monitoring_network_name }}"
      tags: promtail-service
