name: Deploy containers via docker-compose
inputs:
  ssh_identity:
    description: string for known_hosts file
    required: true
  ssh_key:
    description: string for id_ed25519 file
    required: true
  ssh_host:
    description: deploy target host
    required: true
  ssh_port:
    description: deploy target port
    required: true
  tag:
    description: The PANDORA_IMAGES_TAG variable value
    required: true
runs:
  using: composite
  steps:
    -
      name: Put server's SSH key
      uses: ./.github/actions/ssh-keys
      with:
        action: put
        identity: ${{ inputs.ssh_identity }}
        key: ${{ inputs.ssh_key }}
    -
      name: Deploy
      shell: bash
      run: |
        ssh_exec() {
          ssh -T ci@${{ inputs.ssh_host }} -p ${{ inputs.ssh_port }} "$1"
        }
        remote_docker_compose() {
          cat "$GITHUB_WORKSPACE/docker-compose.yml" \
            | ssh_exec "PANDORA_IMAGES_TAG=${{ inputs.tag }} docker-compose --project-name pandora --file - $@"
        }

        remote_docker_compose pull --quiet
        remote_docker_compose up --no-build --detach
        ssh_exec 'docker image prune --all --filter "until=300h" --force'
    -
      name: Destroy server's SSH key
      uses: ./.github/actions/ssh-keys
      with:
        action: destroy
