on:
  push:
    branches:
      - main
    paths-ignore:
      - 'server/**'
      - '.github/workflows/server-config-update.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: The PANDORA_IMAGES_TAG variable value
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_host }}
          username: github
          password: ${{ secrets.registry_password }}
      -
        name: Build web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ${{ secrets.registry_host }}/lib/web:${{ github.run_number }}
          build-args: |
            VUE_APP_API_URL=https://api.pandora-kpop.ru/
      -
        name: Build api
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ secrets.registry_host }}/lib/api:${{ github.run_number }}


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Auto-deploy
        if: ${{ github.event_name == 'push' }}
        uses: ./.github/actions/deploy
        with:
          ssh_identity: ${{ secrets.deploy_target_identity }}
          ssh_key: ${{ secrets.deploy_target_key }}
          ssh_host: ${{ secrets.deploy_target_host }}
          ssh_port: ${{ secrets.deploy_target_port }}
          tag: ${{ github.run_number }}
      -
        name: Manual deploy
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/deploy
        with:
          ssh_identity: ${{ secrets.deploy_target_identity }}
          ssh_key: ${{ secrets.deploy_target_key }}
          ssh_host: ${{ secrets.deploy_target_host }}
          ssh_port: ${{ secrets.deploy_target_port }}
          tag: ${{ github.event.inputs.tag }}
