on:
  push:
    branches:
      - main
    paths-ignore:
      - 'server/**'
      - '.github/workflows/server-config-update.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_host }}
          username: github
          password: ${{ secrets.registry_password }}
      -
        name: Build web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ${{ secrets.registry_host }}/lib/web:${{ github.run_number }}
          build-args: |
            VUE_APP_API_URL=https://api.pandora-kpop.ru/
      -
        name: Build api
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ secrets.registry_host }}/lib/api:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Put server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: put
          identity: ${{ secrets.deploy_target_identity }}
          key: ${{ secrets.deploy_target_key }}
      -
        uses: actions/checkout@v2
      -
        name: Deploy
        shell: bash
        run: |
          remote_docker_compose() {
            cat "$GITHUB_WORKSPACE/docker-compose.yml" \
              | ssh -T \
                  ci@$DEPLOY_TARGET_HOST \
                  -p $DEPLOY_TARGET_PORT \
                  "PANDORA_IMAGES_TAG=$TAG docker-compose --project-name pandora --file - $@"
          }
          remote_docker_compose pull --quiet
          remote_docker_compose up --no-build --detach
        env:
          DEPLOY_TARGET_HOST: ${{ secrets.deploy_target_host }}
          DEPLOY_TARGET_PORT: ${{ secrets.deploy_target_port }}
          TAG: ${{ github.run_number }}
      -
        name: Destroy server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: destroy
