on:
  push:

jobs:

  backup:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Put server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: put
          identity: ${{ secrets.deploy_target_identity }}
          key: ${{ secrets.deploy_target_key }}
      -
        name: Deploy
        shell: bash
        run: |
          ls -la
      -
        name: Destroy server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: destroy