on:
  push:

jobs:

  backup:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Put server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: put
          identity: ${{ secrets.deploy_target_identity }}
          key: ${{ secrets.deploy_target_key }}
      -
        name: Backup
        shell: bash
        run: |
          echo "
            STORAGE_USER=$STORAGE_USER
            STORAGE_PASSWORD=$STORAGE_PASSWORD
            STORAGE_BASE_URI=$STORAGE_BASE_URI
            STORAGE_BACKUPS_REPO=$STORAGE_BACKUPS_REPO
            $(cat ./server/backup-db.sh)
          " | ssh -T ci@$DEPLOY_TARGET_HOST -p $DEPLOY_TARGET_PORT
        env:
          DEPLOY_TARGET_HOST: ${{ secrets.deploy_target_host }}
          DEPLOY_TARGET_PORT: ${{ secrets.deploy_target_port }}
          STORAGE_USER: github
          STORAGE_PASSWORD: ${{ secrets.registry_password }}
          STORAGE_BASE_URI: ${{ secrets.storage_base_uri }}
          STORAGE_BACKUPS_REPO: ${{ secrets.storage_backups_repo }}
      -
        name: Destroy server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: destroy
