name: ci
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create SSH key
        shell: bash
        run: |
          mkdir -v ~/.ssh 
          chmod -v 700 ~/.ssh
          echo "$DEPLOY_TARGET_IDENTITY" > ~/.ssh/known_hosts
          echo "$DEPLOY_TARGET_KEY" > ~/.ssh/id_rsa
          chmod -v 600 ~/.ssh/*
        env:
          DEPLOY_TARGET_IDENTITY: ${{ secrets.deploy_target_identity }}
          DEPLOY_TARGET_KEY: ${{ secrets.deploy_target_key }}
      -
        uses: actions/checkout@v2
      -
        name: SSH into the Production Server
        shell: bash
        run: |
          cat "$GITHUB_WORKSPACE/docker-compose.yml" \
            | ssh \
                -T "$DEPLOY_TARGET_USER@$DEPLOY_TARGET_HOST" \
                -p "$DEPLOY_TARGET_PORT" \
                "docker-compose --project-name pandora --file - up --detach"
        env:
          DEPLOY_TARGET_USER: ${{ secrets.deploy_target_user }}
          DEPLOY_TARGET_HOST: ${{ secrets.deploy_target_host }}
          DEPLOY_TARGET_PORT: ${{ secrets.deploy_target_port }}
      -
        name: Destroy SSH key
        shell: bash
        run: shred -u ~/.ssh/*
