on:
  push:
    branches:
      - main
    paths:
      - 'server/nginx.conf'
      - '.github/workflows/nginx-config-update.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Put server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: put
          identity: ${{ secrets.deploy_target_identity }}
          key: ${{ secrets.deploy_target_key }}
      -
        uses: actions/checkout@v2
      -
        name: Update server configuration
        shell: bash
        run: |
          cat "$GITHUB_WORKSPACE/server/nginx.conf" \
            | ssh -T \
                ci@$DEPLOY_TARGET_HOST \
                -p $DEPLOY_TARGET_PORT \
                "env \$(cat /home/ci/.env | xargs) envsubst '\$PANDORA_WEB_PORT\$PANDORA_API_PORT' > /etc/nginx/sites-enabled/pandora"
          ssh -T \
              ci@$DEPLOY_TARGET_HOST \
              -p $DEPLOY_TARGET_PORT \
              "sudo nginx -t && sudo nginx -s reload"
        env:
          DEPLOY_TARGET_HOST: ${{ secrets.deploy_target_host }}
          DEPLOY_TARGET_PORT: ${{ secrets.deploy_target_port }}
          TAG: ${{ github.run_number }}
      -
        name: Destroy server's SSH key
        uses: ./.github/actions/ssh-keys
        with:
          action: destroy
